// Automatically generated by flapigen
package com.example.docxgenerator.lib;


public final class RustLog {

    static {
        System.loadLibrary("docx_lib");
    }

    public static native void initialiseLogging();

    private RustLog() {}
}